// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0kPJKSOU4qtXrvddyAZFHeXQY2LMrz_M',
    appId: '1:51746516421:web:e77c88b9d209063446afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    authDomain: 'mile-cab-app.firebaseapp.com',
    storageBucket: 'mile-cab-app.appspot.com',
    measurementId: 'G-763ZNR0FZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIYD2kRxQohHb4I5bbLbML3mfOnx1x5II',
    appId: '1:51746516421:android:fef2e66ce38b0f4e46afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    storageBucket: 'mile-cab-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYuIucLF8TsHUwQ9WjVY9juDmP1AbJsM',
    appId: '1:51746516421:ios:998cead7dcf5dc3446afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    storageBucket: 'mile-cab-app.appspot.com',
    androidClientId: '51746516421-1huqtkqb17886cqk92ftdsiub6ortml6.apps.googleusercontent.com',
    iosClientId: '51746516421-q816vlgur2vsfs1hdicap87467aed9en.apps.googleusercontent.com',
    iosBundleId: 'com.example.primeTaxiFlutterUiKit',
  );
}
